name: owg-log
markdown: kramdown
highlighter: rouge
baseurl: /owg-log
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
     path: ""
     type: posts
    values:
      layout: post
